Attribute VB_Name = "modPivots"
Option Explicit
'==============================================================================
' Rebuilds the Pivot Explorer sheet: three pivot tables over the raw data
' plus interactive slicers, created entirely from code.
'==============================================================================

Public Sub BuildPivots()
    Dim ws As Worksheet: Set ws = GetWS("PivotExplorer")
    Dim i As Long

    For i = ThisWorkbook.SlicerCaches.Count To 1 Step -1
        If LCase(Left(ThisWorkbook.SlicerCaches(i).Name, 3)) = "slc" Then
            ThisWorkbook.SlicerCaches(i).Delete
        End If
    Next i
    Dim pt As PivotTable
    For Each pt In ws.PivotTables
        pt.TableRange2.Clear
    Next pt
    ws.Cells.Clear
    ws.Cells.Interior.Color = ClrLight()

    With ws.Range("A1")
        .Value = "PIVOT EXPLORER  -  slice the workforce any way you need"
        .Font.Size = 14: .Font.Bold = True: .Font.Color = ClrNavy()
    End With
    ws.Range("A2").Value = "Generated by VBA on " & Format(Now, "dd-mmm-yyyy hh:nn")
    ws.Range("A2").Font.Size = 9
    ws.Range("A2").Font.Color = ClrGrey()

    Dim pc As PivotCache

    ' ---- 1. headcount cube: Department x Facility, filtered to Active ----------
    Set pc = ThisWorkbook.PivotCaches.Create(xlDatabase, "tblEmployees")
    Set pt = pc.CreatePivotTable(ws.Range("A5"), "ptHeadcount")
    With pt
        .PivotFields("Department").Orientation = xlRowField
        .PivotFields("Facility").Orientation = xlColumnField
        .PivotFields("Status").Orientation = xlPageField
        On Error Resume Next
        .PivotFields("Status").CurrentPage = "Active"
        On Error GoTo 0
        .AddDataField .PivotFields("EmployeeID"), "Employees", xlCount
        .TableStyle2 = "PivotStyleMedium9"
        .ColumnGrand = True
        .RowGrand = True
    End With

    ' slicers wired to the headcount cube
    Dim sc As SlicerCache
    Set sc = ThisWorkbook.SlicerCaches.Add2(pt, "Gender", "slcGender")
    sc.Slicers.Add ws, , "sliGender", "Gender", _
        ws.Range("M5").Top, ws.Range("M5").Left, 150, 96
    Set sc = ThisWorkbook.SlicerCaches.Add2(pt, "NationalityGroup", "slcNatGroup")
    sc.Slicers.Add ws, , "sliNatGroup", "Saudi / Non-Saudi", _
        ws.Range("M5").Top + 104, ws.Range("M5").Left, 150, 96
    Set sc = ThisWorkbook.SlicerCaches.Add2(pt, "EmploymentType", "slcEmpType")
    sc.Slicers.Add ws, , "sliEmpType", "Employment Type", _
        ws.Range("M5").Top + 208, ws.Range("M5").Left, 150, 120

    ' ---- 2. leave days by type ---------------------------------------------------
    Set pc = ThisWorkbook.PivotCaches.Create(xlDatabase, "tblLeave")
    Set pt = pc.CreatePivotTable(ws.Range("A26"), "ptLeave")
    With pt
        .PivotFields("LeaveType").Orientation = xlRowField
        .AddDataField .PivotFields("Days"), "Leave Days", xlSum
        .TableStyle2 = "PivotStyleMedium9"
    End With

    ' ---- 3. training investment by category ----------------------------------------
    Set pc = ThisWorkbook.PivotCaches.Create(xlDatabase, "tblTraining")
    Set pt = pc.CreatePivotTable(ws.Range("E26"), "ptTraining")
    With pt
        .PivotFields("Category").Orientation = xlRowField
        .AddDataField .PivotFields("Hours"), "Hours ", xlSum
        .AddDataField .PivotFields("CostSAR"), "Cost (SAR)", xlSum
        .TableStyle2 = "PivotStyleMedium9"
    End With

    ws.Columns("A:K").AutoFit
    ws.Tab.Color = ClrNavy()
End Sub
