{
  "name": "816011e3-d74b-4954-88e6-6488bbffe492",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Employees",
        "lineageTag": "191bcdbb-f34f-4a37-8af5-e40584424008",
        "columns": [
          {
            "name": "EmployeeID",
            "dataType": "string",
            "sourceColumn": "EmployeeID",
            "lineageTag": "4cfe7cc8-4a70-4f46-b00a-bd5187dac34f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FullName",
            "dataType": "string",
            "sourceColumn": "FullName",
            "lineageTag": "f9fb8d9c-08c7-4326-a80b-f06ac05a63d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "lineageTag": "31408c56-c7c8-458f-9dc7-b8010314af63",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nationality",
            "dataType": "string",
            "sourceColumn": "Nationality",
            "lineageTag": "3d53c732-3933-4a33-8d59-eb32d4ff4115",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NationalityGroup",
            "dataType": "string",
            "sourceColumn": "NationalityGroup",
            "lineageTag": "47bf1bf9-abcb-4323-aa9d-d852eca7fec5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department",
            "lineageTag": "0772b07f-6675-4bae-97c4-206d7ef891a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "JobTitle",
            "dataType": "string",
            "sourceColumn": "JobTitle",
            "lineageTag": "3f20825e-bee2-4317-a693-ca34f8db5311",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Facility",
            "dataType": "string",
            "sourceColumn": "Facility",
            "lineageTag": "2d5ec1fa-f3c2-4a4a-a55e-809fae19a437",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HireDate",
            "dataType": "dateTime",
            "sourceColumn": "HireDate",
            "lineageTag": "d3d23334-c1a4-454e-b546-7cbf52f00fc5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "TerminationDate",
            "dataType": "dateTime",
            "sourceColumn": "TerminationDate",
            "lineageTag": "0718bf40-ca8e-4c5e-818c-50bd65c47da8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "TerminationReason",
            "dataType": "string",
            "sourceColumn": "TerminationReason",
            "lineageTag": "677b02ed-0ad7-4c40-837f-bc4eba126be0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TerminationType",
            "dataType": "string",
            "sourceColumn": "TerminationType",
            "lineageTag": "6bd4f6db-96b2-4e19-9eae-cfe2ddaf935e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthlySalarySAR",
            "dataType": "int64",
            "sourceColumn": "MonthlySalarySAR",
            "lineageTag": "cdee5182-e7e3-46bc-b26e-cd98371494fb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate",
            "lineageTag": "b363a66f-e1c3-472c-a5cf-fb13fdb2ab1b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "AgeBand",
            "dataType": "string",
            "sourceColumn": "AgeBand",
            "lineageTag": "84cc68df-ee32-4ed5-b550-34faa5cad93a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TenureBand",
            "dataType": "string",
            "sourceColumn": "TenureBand",
            "lineageTag": "9309985f-b13c-494c-9af8-09722641d3e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Grade",
            "dataType": "string",
            "sourceColumn": "Grade",
            "lineageTag": "a11e7c59-831d-4a2a-aae8-0eb3b5e1c6db",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PerformanceRating",
            "dataType": "double",
            "sourceColumn": "PerformanceRating",
            "lineageTag": "36d07ea3-4c89-49d2-9028-90709c7ae3ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0"
          },
          {
            "name": "EmploymentType",
            "dataType": "string",
            "sourceColumn": "EmploymentType",
            "lineageTag": "33ed3a1d-8a20-4545-8829-a79df255d39d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employees",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"xX1bkxu3te5fYfnpnNpbqQYafUHVeRnbiSU7Iysa76SSXfuhR0OJtIakTA6tM/71\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"EmployeeID\" = _t, #\"FullName\" = _t, #\"Gender\" = _t, #\"Nationality\" = _t, #\"NationalityGroup\" = _t, #\"Department\" = _t, #\"JobTitle\" = _t, #\"Facility\" = _t, #\"HireDate\" = _t, #\"TerminationDate\" = _t, #\"TerminationReason\" = _t, #\"TerminationType\" = _t, #\"MonthlySalarySAR\" = _t, #\"BirthDate\" = _t, #\"AgeBand\" = _t, #\"TenureBand\" = _t, #\"Grade\" = _t, #\"PerformanceRating\" = _t, #\"EmploymentType\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"HireDate\", type date}, {\"TerminationDate\", type date}, {\"MonthlySalarySAR\", Int64.Type}, {\"BirthDate\", type date}, {\"PerformanceRating\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Recruitment",
        "lineageTag": "6bb78926-7c66-4db8-8484-ad93684e330f",
        "columns": [
          {
            "name": "RequisitionID",
            "dataType": "string",
            "sourceColumn": "RequisitionID",
            "lineageTag": "e9dbd7fd-b4e6-4bba-9c9c-1a9c19e1ad15",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Position",
            "dataType": "string",
            "sourceColumn": "Position",
            "lineageTag": "62d1f509-9b97-4ab0-9aa4-ca95862f3f6c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department",
            "lineageTag": "df73bbe1-4c7a-4c4e-935a-334ee03b14dc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Facility",
            "dataType": "string",
            "sourceColumn": "Facility",
            "lineageTag": "2673ae1b-f5a9-4de1-8f5e-377faa3ac2fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PostingDate",
            "dataType": "dateTime",
            "sourceColumn": "PostingDate",
            "lineageTag": "59f1f70a-38cf-4636-9d5b-9c4a932d3e13",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "FilledDate",
            "dataType": "dateTime",
            "sourceColumn": "FilledDate",
            "lineageTag": "3af20218-2542-4336-b1f0-f7f9b859370a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "ac442aeb-db07-4f3e-ba43-1a23d01b8f25",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DaysToFill",
            "dataType": "int64",
            "sourceColumn": "DaysToFill",
            "lineageTag": "d18887f0-6386-470b-9a39-aa4110480662",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "Applications",
            "dataType": "int64",
            "sourceColumn": "Applications",
            "lineageTag": "13e1b7ec-5803-46ae-864d-b24e3c3f0b7a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "OffersMade",
            "dataType": "int64",
            "sourceColumn": "OffersMade",
            "lineageTag": "2f33492b-0307-4cfe-ad7a-20feb85a5959",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "OffersAccepted",
            "dataType": "int64",
            "sourceColumn": "OffersAccepted",
            "lineageTag": "b4d49502-d58c-463b-b896-3dfac72bd21d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "Source",
            "dataType": "string",
            "sourceColumn": "Source",
            "lineageTag": "b4ef9e6d-bd74-4534-8ba4-3b8f543aee00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Recruitment",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rVxbc9u2Ev4rGj9Hc4gLQfAxTdvjnGlOUzszfej0gbFpmxNZ8khyctxff7ALEQII\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"RequisitionID\" = _t, #\"Position\" = _t, #\"Department\" = _t, #\"Facility\" = _t, #\"PostingDate\" = _t, #\"FilledDate\" = _t, #\"Status\" = _t, #\"DaysToFill\" = _t, #\"Applications\" = _t, #\"OffersMade\" = _t, #\"OffersAccepted\" = _t, #\"Source\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PostingDate\", type date}, {\"FilledDate\", type date}, {\"DaysToFill\", Int64.Type}, {\"Applications\", Int64.Type}, {\"OffersMade\", Int64.Type}, {\"OffersAccepted\", Int64.Type}}, \"en-US\")",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Training",
        "lineageTag": "6d08ab14-b118-4882-8b04-b1c528207fd3",
        "columns": [
          {
            "name": "TrainingID",
            "dataType": "string",
            "sourceColumn": "TrainingID",
            "lineageTag": "42bcf6cd-6a72-4ea8-a5fa-0d4de2d2e67f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EmployeeID",
            "dataType": "string",
            "sourceColumn": "EmployeeID",
            "lineageTag": "25cb5b4e-154b-4710-910a-7b7e93705b38",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Course",
            "dataType": "string",
            "sourceColumn": "Course",
            "lineageTag": "71ed10a6-8bfe-43e4-851a-78331c050d06",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "0ad0d5bf-b991-4a1b-8f06-883045a3817f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "lineageTag": "95bc9c75-1ecc-492a-88fa-9a6bcad08aa0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "Hours",
            "dataType": "int64",
            "sourceColumn": "Hours",
            "lineageTag": "884f7127-d43b-4c13-ba4e-2d8855867995",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "CostSAR",
            "dataType": "int64",
            "sourceColumn": "CostSAR",
            "lineageTag": "c27f9da2-1bb9-4de2-b5a2-18939fdf4049",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "CompletionStatus",
            "dataType": "string",
            "sourceColumn": "CompletionStatus",
            "lineageTag": "678f0be7-fa47-481b-82f8-4a6b3f9a6c47",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Training",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tV3Ljly5kf2VghazcmH4CL6WliCPG2gbRrd3hhdldcldgCw1JLUffz95yZskg+LJ\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"TrainingID\" = _t, #\"EmployeeID\" = _t, #\"Course\" = _t, #\"Category\" = _t, #\"Date\" = _t, #\"Hours\" = _t, #\"CostSAR\" = _t, #\"CompletionStatus\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}, {\"Hours\", Int64.Type}, {\"CostSAR\", Int64.Type}}, \"en-US\")",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Leave",
        "lineageTag": "745c2a79-721b-4117-9c57-6e71a8d91d20",
        "columns": [
          {
            "name": "LeaveID",
            "dataType": "string",
            "sourceColumn": "LeaveID",
            "lineageTag": "01d0e125-c02a-43ce-85cf-d9765fb83e36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EmployeeID",
            "dataType": "string",
            "sourceColumn": "EmployeeID",
            "lineageTag": "d69d9c8e-fa19-4641-85dc-69a40a9ff1c0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LeaveType",
            "dataType": "string",
            "sourceColumn": "LeaveType",
            "lineageTag": "a81ace0c-4934-4d99-8b1c-59e229719e8f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate",
            "lineageTag": "1c7a8373-831a-4c8c-b168-bf4d33b7249a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy"
          },
          {
            "name": "Days",
            "dataType": "int64",
            "sourceColumn": "Days",
            "lineageTag": "8331746a-4266-40b7-a03e-3e2ab95f5a7b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          }
        ],
        "partitions": [
          {
            "name": "Leave",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jV1BjzW5bfwve/YHiBJJScccguRgn4LkYviwcBbBOskiMOyD/33mtd6bR5ZK0wPs\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"LeaveID\" = _t, #\"EmployeeID\" = _t, #\"LeaveType\" = _t, #\"StartDate\" = _t, #\"Days\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"StartDate\", type date}, {\"Days\", Int64.Type}}, \"en-US\")",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimDepartment",
        "lineageTag": "39df8100-43a6-4c5e-8864-4cfeaab85dd0",
        "columns": [
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department",
            "lineageTag": "bf06b4ba-7656-4506-9ee0-a5ed4e083e9c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "Division",
            "lineageTag": "8ba47855-94fe-47c9-82dd-5210d01f73eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDepartment",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bU9BDoMwDPsK6pk9YmKaNmlCCHZDHLLS0Ug0QWk7id+vO3AY5ZbYju30vWrs6lEjkFelqmYk1DCroexVHcUjTXu4sSAO9LrHH/BigcCSMS2MyDNPGXExFNKYBaRGHKwRWLKT8+jS5kNKQqbE1kynP8UtOqCiNZ6jaOOPJFckIG2OqDu9Ob33My+eRlvaimfKKvrAzkjRGfngsVsXl4UlbJK8zPAF\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Department\" = _t, #\"Division\" = _t])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimFacility",
        "lineageTag": "83358611-f065-4340-965a-7df7e8453b98",
        "columns": [
          {
            "name": "Facility",
            "dataType": "string",
            "sourceColumn": "Facility",
            "lineageTag": "9cb0db66-87fd-429e-8356-17a6979d2f1f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "f13afd3e-aa3c-4ded-9367-3b58f6ace90e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "b100f800-cafe-4431-96e2-ec0b8dd87c14",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FacilityType",
            "dataType": "string",
            "sourceColumn": "FacilityType",
            "lineageTag": "acd86a4d-f051-4e89-a6d2-d9cadf567bf1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimFacility",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckxKTS1S8MgvLsgsScxR0FUIzkgsSkzLrEzMUNJR8kpNSQEzwlOLS1KL8oAsmFKlWB2Ybt/UlMxkoGbn1DygIqAZjlWZVbhNQFWOz5zgxLxEapjjlFiemJJJoilIYRIEdEQKSBucAVJdBAwE4sLDKbEkIxG7duI94ZKYm5uYC9QCZ7gmkh4UvonZ2eAQgDNwB0UsAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Facility\" = _t, #\"City\" = _t, #\"Region\" = _t, #\"FacilityType\" = _t])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "eab3b5ce-49ec-4c12-b8d8-79b53d93cd34",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "[Date]",
            "lineageTag": "7e561fd9-40cc-45d9-8f50-0f383b0d5607",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd-mmm-yyyy",
            "isKey": true,
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "[Year]",
            "lineageTag": "793e43a4-095d-4a81-99fe-d6dc30846871",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "[Month Number]",
            "lineageTag": "747798e4-167c-4c5a-9ac4-96374b5731fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true,
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "[Month]",
            "lineageTag": "b307b863-0de2-4255-8873-9a3ee862ed6f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "Month Number",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          },
          {
            "name": "MonthStart",
            "dataType": "dateTime",
            "sourceColumn": "[MonthStart]",
            "lineageTag": "34316aa3-2e26-4d35-8ff1-a354e62e6d52",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "mmm yyyy",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "[Quarter]",
            "lineageTag": "db6aac0b-c5b0-4b97-bc85-2363f4427366",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          },
          {
            "name": "Year-Month",
            "dataType": "string",
            "sourceColumn": "[Year-Month]",
            "lineageTag": "766046b3-015f-42f8-b841-f5f906378f28",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "ADDCOLUMNS (",
                "    CALENDAR ( DATE ( 2020, 1, 1 ), DATE ( 2026, 6, 30 ) ),",
                "    \"Year\", YEAR ( [Date] ),",
                "    \"Month Number\", MONTH ( [Date] ),",
                "    \"Month\", FORMAT ( [Date], \"MMM\" ),",
                "    \"MonthStart\", DATE ( YEAR ( [Date] ), MONTH ( [Date] ), 1 ),",
                "    \"Quarter\", \"Q\" & FORMAT ( [Date], \"Q\" ),",
                "    \"Year-Month\", FORMAT ( [Date], \"YYYY-MM\" )",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "HR Measures",
        "lineageTag": "0e4a4894-ff01-4cf8-9f5a-00486fddc733",
        "columns": [
          {
            "name": "Col",
            "dataType": "int64",
            "sourceColumn": "Col",
            "lineageTag": "bd617a73-aeda-4e0b-9bd2-e864377ee283",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "HR Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #table ( type table [ Col = Int64.Type ], {} )",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Headcount",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    COUNTROWS ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ) )"
            ],
            "lineageTag": "ebb88939-5cc8-46ab-8618-c53a1a1ea631",
            "formatString": "#,0",
            "displayFolder": "Workforce"
          },
          {
            "name": "Saudi Headcount",
            "expression": [
              "CALCULATE ( [Headcount], Employees[NationalityGroup] = \"Saudi\" )"
            ],
            "lineageTag": "53c341d5-97ca-43cf-83d7-8c7c0828fd10",
            "formatString": "#,0",
            "displayFolder": "Saudization"
          },
          {
            "name": "Non-Saudi Headcount",
            "expression": [
              "[Headcount] - [Saudi Headcount]"
            ],
            "lineageTag": "8165e71b-bb75-4a12-8498-58b113a5b1ea",
            "formatString": "#,0",
            "displayFolder": "Saudization"
          },
          {
            "name": "Saudization %",
            "expression": [
              "DIVIDE ( [Saudi Headcount], [Headcount] )"
            ],
            "lineageTag": "54d79d81-ae95-45f7-a5fd-cb5fefb7e6ae",
            "formatString": "0.0%",
            "displayFolder": "Saudization"
          },
          {
            "name": "Saudization Target",
            "expression": [
              "0.40"
            ],
            "lineageTag": "0fca3081-b6f4-4cdf-9ddb-e55ccadc00c2",
            "formatString": "0%",
            "displayFolder": "Saudization"
          },
          {
            "name": "Female Headcount",
            "expression": [
              "CALCULATE ( [Headcount], Employees[Gender] = \"Female\" )"
            ],
            "lineageTag": "9ceb8feb-f83b-4ed5-9405-ad5c8d47f9d3",
            "formatString": "#,0",
            "displayFolder": "Workforce"
          },
          {
            "name": "Female Ratio %",
            "expression": [
              "DIVIDE ( [Female Headcount], [Headcount] )"
            ],
            "lineageTag": "ff7fffe0-23a5-420f-982b-975c8d9f4756",
            "formatString": "0.0%",
            "displayFolder": "Workforce"
          },
          {
            "name": "Hires",
            "expression": [
              "COUNTROWS ( FILTER ( Employees, Employees[HireDate] >= MIN ( 'Date'[Date] ) && Employees[HireDate] <= MAX ( 'Date'[Date] ) ) )"
            ],
            "lineageTag": "11c26551-9ba7-439e-a5a8-1291c4869e03",
            "formatString": "#,0",
            "displayFolder": "Attrition"
          },
          {
            "name": "Terminations",
            "expression": [
              "COUNTROWS ( FILTER ( Employees, NOT ISBLANK ( Employees[TerminationDate] ) && Employees[TerminationDate] >= MIN ( 'Date'[Date] ) && Employees[TerminationDate] <= MAX ( 'Date'[Date] ) ) )"
            ],
            "lineageTag": "165be5cb-843f-44f6-983d-0838a843ed26",
            "formatString": "#,0",
            "displayFolder": "Attrition"
          },
          {
            "name": "Voluntary Terminations",
            "expression": [
              "CALCULATE ( [Terminations], Employees[TerminationType] = \"Voluntary\" )"
            ],
            "lineageTag": "1e20e87a-50c3-490d-ada6-49cb016153cc",
            "formatString": "#,0",
            "displayFolder": "Attrition"
          },
          {
            "name": "Voluntary Share %",
            "expression": [
              "DIVIDE ( [Voluntary Terminations], [Terminations] )"
            ],
            "lineageTag": "b7ce9d10-d7dd-4327-aa3b-03134e9dc17a",
            "formatString": "0.0%",
            "displayFolder": "Attrition"
          },
          {
            "name": "Attrition Rate %",
            "expression": [
              "DIVIDE ( [Terminations], AVERAGEX ( VALUES ( 'Date'[MonthStart] ), [Headcount] ) )"
            ],
            "lineageTag": "ef5bf2e7-fae3-4aa1-8ff8-813cfaccf623",
            "formatString": "0.0%",
            "displayFolder": "Attrition"
          },
          {
            "name": "Net Headcount Change",
            "expression": [
              "[Hires] - [Terminations]"
            ],
            "lineageTag": "56cdc133-9eba-416e-8148-e9a39f3fe86d",
            "formatString": "+#,0;-#,0;0",
            "displayFolder": "Attrition"
          },
          {
            "name": "Avg Tenure (Years)",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    AVERAGEX ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ), DATEDIFF ( Employees[HireDate], _d, DAY ) / 365.25 )"
            ],
            "lineageTag": "41f93c0d-a0b7-4dfe-bd23-d51a04fc6c80",
            "formatString": "0.0",
            "displayFolder": "Workforce"
          },
          {
            "name": "Avg Age",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    AVERAGEX ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ), DATEDIFF ( Employees[BirthDate], _d, DAY ) / 365.25 )"
            ],
            "lineageTag": "83273126-3065-4da5-854b-b7565cd08559",
            "formatString": "0.0",
            "displayFolder": "Workforce"
          },
          {
            "name": "Monthly Payroll (SAR)",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    SUMX ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ), Employees[MonthlySalarySAR] )"
            ],
            "lineageTag": "2f420ebc-7671-477d-b2e7-c94dacd4546f",
            "formatString": "#,0",
            "displayFolder": "Compensation"
          },
          {
            "name": "Avg Monthly Salary (SAR)",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    AVERAGEX ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ), Employees[MonthlySalarySAR] )"
            ],
            "lineageTag": "4f9ce7ea-055d-42be-a00c-f03a46a5baf8",
            "formatString": "#,0",
            "displayFolder": "Compensation"
          },
          {
            "name": "Median Salary (SAR)",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    MEDIANX ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ), Employees[MonthlySalarySAR] )"
            ],
            "lineageTag": "9570106f-b061-497a-8ec0-df99adaf8262",
            "formatString": "#,0",
            "displayFolder": "Compensation"
          },
          {
            "name": "Avg Performance Rating",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "RETURN",
              "    AVERAGEX ( FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) ), Employees[PerformanceRating] )"
            ],
            "lineageTag": "307f3689-7f11-4609-bf07-9c126f536888",
            "formatString": "0.00",
            "displayFolder": "Performance"
          },
          {
            "name": "High Performers %",
            "expression": [
              " ",
              "VAR _d = MAX ( 'Date'[Date] )",
              "VAR _act = FILTER ( Employees, Employees[HireDate] <= _d && ( ISBLANK ( Employees[TerminationDate] ) || Employees[TerminationDate] > _d ) )",
              "RETURN",
              "    DIVIDE ( COUNTROWS ( FILTER ( _act, Employees[PerformanceRating] >= 4.5 ) ), COUNTROWS ( _act ) )"
            ],
            "lineageTag": "2bcf7230-968d-40b0-917f-6dc328aaa667",
            "formatString": "0.0%",
            "displayFolder": "Performance"
          },
          {
            "name": "Open Positions",
            "expression": [
              "CALCULATE ( COUNTROWS ( Recruitment ), Recruitment[Status] = \"Open\" )"
            ],
            "lineageTag": "2758f035-34e5-4f7b-ae23-db311218ebc4",
            "formatString": "#,0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Positions Filled",
            "expression": [
              "CALCULATE ( COUNTROWS ( Recruitment ), Recruitment[Status] = \"Filled\" )"
            ],
            "lineageTag": "dc5a162c-d587-4799-9afe-03bdc8b10e15",
            "formatString": "#,0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Avg Time to Fill (Days)",
            "expression": [
              "CALCULATE ( AVERAGE ( Recruitment[DaysToFill] ), Recruitment[Status] = \"Filled\" )"
            ],
            "lineageTag": "858332bb-2761-4486-b422-c8c1e4440497",
            "formatString": "0.0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Total Applications",
            "expression": [
              "SUM ( Recruitment[Applications] )"
            ],
            "lineageTag": "f8f5caf9-5597-47b5-81d4-0ee49653d13f",
            "formatString": "#,0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Offers Made",
            "expression": [
              "SUM ( Recruitment[OffersMade] )"
            ],
            "lineageTag": "82c66c94-3fc3-470d-baa0-078fab63bcb8",
            "formatString": "#,0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Offers Accepted",
            "expression": [
              "SUM ( Recruitment[OffersAccepted] )"
            ],
            "lineageTag": "3376681e-7f85-48bd-a73b-7faea02bbbbd",
            "formatString": "#,0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Offer Acceptance %",
            "expression": [
              "DIVIDE ( [Offers Accepted], [Offers Made] )"
            ],
            "lineageTag": "a1398522-b2df-45f5-8b58-15184e532548",
            "formatString": "0.0%",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Applications per Hire",
            "expression": [
              "DIVIDE ( [Total Applications], [Positions Filled] )"
            ],
            "lineageTag": "701f7bbd-9b0d-4649-97db-3b6d3666a369",
            "formatString": "0.0",
            "displayFolder": "Recruitment"
          },
          {
            "name": "Training Hours",
            "expression": [
              "SUM ( Training[Hours] )"
            ],
            "lineageTag": "45294810-04e4-4ef2-b124-b1a8a2ba5dbf",
            "formatString": "#,0",
            "displayFolder": "Training"
          },
          {
            "name": "Training Cost (SAR)",
            "expression": [
              "SUM ( Training[CostSAR] )"
            ],
            "lineageTag": "01fdd440-4212-460b-8c32-7b01efe2dd94",
            "formatString": "#,0",
            "displayFolder": "Training"
          },
          {
            "name": "Trainings Delivered",
            "expression": [
              "COUNTROWS ( Training )"
            ],
            "lineageTag": "896a0797-ec0d-4812-8c8c-7804487eb1c3",
            "formatString": "#,0",
            "displayFolder": "Training"
          },
          {
            "name": "Training Completion %",
            "expression": [
              "DIVIDE ( CALCULATE ( COUNTROWS ( Training ), Training[CompletionStatus] = \"Completed\" ), COUNTROWS ( Training ) )"
            ],
            "lineageTag": "a3f88a43-6956-4aab-bd83-64fc0eb18869",
            "formatString": "0.0%",
            "displayFolder": "Training"
          },
          {
            "name": "Training Hours per Employee",
            "expression": [
              "DIVIDE ( [Training Hours], [Headcount] )"
            ],
            "lineageTag": "2b2d7824-84d6-4250-9298-dea27fe908de",
            "formatString": "0.0",
            "displayFolder": "Training"
          },
          {
            "name": "Leave Days",
            "expression": [
              "SUM ( 'Leave'[Days] )"
            ],
            "lineageTag": "3b54c6e6-d558-42b9-a915-f563f42acbf3",
            "formatString": "#,0",
            "displayFolder": "Leave"
          },
          {
            "name": "Sick Leave Days",
            "expression": [
              "CALCULATE ( SUM ( 'Leave'[Days] ), 'Leave'[LeaveType] = \"Sick\" )"
            ],
            "lineageTag": "a83c1b2e-6413-4afd-becf-8430f32ae069",
            "formatString": "#,0",
            "displayFolder": "Leave"
          },
          {
            "name": "Absenteeism %",
            "expression": [
              "DIVIDE ( [Sick Leave Days], [Headcount] * COUNTROWS ( VALUES ( 'Date'[MonthStart] ) ) * 22 )"
            ],
            "lineageTag": "cd9cf320-1766-441e-abe6-b55983fba346",
            "formatString": "0.00%",
            "displayFolder": "Leave"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "2a4bfa0d-b991-4f65-9af3-bd2ba754a86e",
        "fromTable": "Leave",
        "fromColumn": "EmployeeID",
        "toTable": "Employees",
        "toColumn": "EmployeeID"
      },
      {
        "name": "bd6fcd60-1a53-4625-8a17-72f555992ef6",
        "fromTable": "Training",
        "fromColumn": "EmployeeID",
        "toTable": "Employees",
        "toColumn": "EmployeeID"
      },
      {
        "name": "2e47ddb4-6896-47c5-8541-0dd86c13c887",
        "fromTable": "Leave",
        "fromColumn": "StartDate",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "bc046037-9d52-4fc0-b16e-1891f262d98d",
        "fromTable": "Training",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "cc744753-b9d8-4371-be0c-30076bcd1167",
        "fromTable": "Recruitment",
        "fromColumn": "PostingDate",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "5a5b6451-a470-43f3-9712-2ebff2a070ae",
        "fromTable": "Employees",
        "fromColumn": "Department",
        "toTable": "DimDepartment",
        "toColumn": "Department"
      },
      {
        "name": "bdd6103c-f6cf-417d-8829-d0187ef6e8d8",
        "fromTable": "Recruitment",
        "fromColumn": "Department",
        "toTable": "DimDepartment",
        "toColumn": "Department"
      },
      {
        "name": "4902a4ab-2fb8-4339-b02e-5ec4785f2fcb",
        "fromTable": "Employees",
        "fromColumn": "Facility",
        "toTable": "DimFacility",
        "toColumn": "Facility"
      },
      {
        "name": "801edad9-87be-4c25-971c-ecfd643c2e13",
        "fromTable": "Recruitment",
        "fromColumn": "Facility",
        "toTable": "DimFacility",
        "toColumn": "Facility"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Employees\", \"Recruitment\", \"Training\", \"Leave\", \"DimDepartment\", \"DimFacility\", \"HR Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.0.0 (Main)"
      }
    ]
  }
}